name: Build Prospera APK
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
          
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          
      - name: Create Clean Flutter Project Automatically
        run: |
          flutter create prospera_app --org com.prospera --project-name prospera_app
          cp main.dart prospera_app/lib/main.dart

      - name: Build APK File
        run: |
          cd prospera_app
          flutter build apk --release
          
      - name: Upload Finished APK
        uses: actions/upload-artifact@v4
        with:
          name: prospera-wallet-apk
          path: prospera_app/build/app/outputs/flutter-apk/app-release.apk
          
